### PR TITLE
New problem candidates

### PR DESCRIPTION
**Pull request by bjorgve**

### CODE REVIEW

**Review by ilfreddy — APPROVED** [review]

**Comment by ilfreddy** [comment]
@robertodr can you merge this, or alternatively, you can grant me write access

**Comment by bjorgve** [comment]
@ilfreddy think I invited you to own this repo

**Comment by bjorgve** [comment]
Maybe we can leave it here, then merge it with all new exercises after the semester is over? Then we can add the things that was successful and remove the things that was not as successful

**Comment by robertodr** [comment]
> @robertodr can you merge this, or alternatively, you can grant me write access

You were invited as an admin a couple of months ago, if I recall correctly. Check your email

**Comment by ilfreddy** [comment]
Can you resend the invitation?

**Pull request merged**
